### PR TITLE
per #116 darker color for pending ping

### PR DESCRIPTION
**Pull request by travis-humbert**
Changed the font color of the ping elements on the /status page from "yellow" to "orangered" to be more legible

### CODE REVIEW

**Comment by weddleben** [comment]
thank you, Travis! this color is much more readable, but it's so similar to the existing red color that I cannot tell the difference.
ss

**Review by weddleben — CHANGES_REQUESTED** [review]
this color is too similar to red

**Comment by travis-humbert** [comment]
Hey Ben - you're right about that orange being too similar to red. Thanks for catching that. I've gone through and changed it from "orange red" to just "orange." Let me know if 

1) that color works - it can be changed quite easily

and 

2) the process of changing/updating the pull request was done correctly. Not that I aspire to make mistakes, but it's good in learning how to go about correcting them.

Thanks for your patience!

**Review by weddleben — COMMENTED** [review]
I downloaded your branch and checked the change, but I think this is still too similar to red. There's not enough of a contrast between pending (yellow/orange) and failure (red).

This is my fault, Travis, so no worries! I think we'll just leave it as-is - yellow. The main point of this was to practice cloning and making changes and PRs and all that stuff. I will try to come up with some other issues for you to tackle. I'll close this PR and the original issue.

**Comment by weddleben** [comment]
unfortunately I think we'll stick with the existing color (for now). thanks for your work on this and hope you got some good practice!

**Comment by travis-humbert** [comment]
Not a problem at all!  I wondered about even going with Gold or another color that was a darker yellow, but they were all either too light or too close to red. But yeah, this was definitely good practice, so thank you for that!

**Pull request closed without merging**
